### ISSUE TITLE
Cannot send commands to Craftassist Agent through Minecraft Chat

### ISSUE THREAD

**Issue by aqibisbiqa** [facebookresearch/fairo#1182]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

When trying to send commands to Craftassist agent through the chat interface in Minecraft, I obtain the following error:

```
ERROR:root:Default handler caught exception, db_log_idx=41990
Traceback (most recent call last):
  File "/private/home/aqib/fairo/agents/core.py", line 21, in start
    self.step()
  File "/private/home/aqib/fairo/agents/droidlet_agent.py", line 301, in step
    super().step()
  File "/private/home/aqib/fairo/agents/core.py", line 26, in step
    self.perceive()
  File "agents/craftassist/craftassist_agent.py", line 275, in perceive
    super().perceive()
  File "/private/home/aqib/fairo/agents/droidlet_agent.py", line 366, in perceive
    self.process_language_perception(speaker, chat, preprocessed_chat, chat_parse)
  File "/private/home/aqib/fairo/agents/droidlet_agent.py", line 340, in process_language_perception
    self.memory.get_player_by_name(speaker).memid, preprocessed_chat
AttributeError: 'NoneType' object has no attribute 'memid'
2022-05-31 11:18:31,146 [droidlet_agent.py:272 - handle_exception() ERROR]: Default handler caught exception, db_log_idx=41990
Traceback (most recent call last):
  File "/private/home/aqib/fairo/agents/core.py", line 21, in start
    self.step()
  File "/private/home/aqib/fairo/agents/droidlet_agent.py", line 301, in step
    super().step()
  File "/private/home/aqib/fairo/agents/core.py", line 26, in step
    self.perceive()
  File "agents/craftassist/craftassist_agent.py", line 275, in perceive
    super().perceive()
  File "/private/home/aqib/fairo/agents/droidlet_agent.py", line 366, in perceive
    self.process_language_perception(speaker, chat, preprocessed_chat, chat_parse)
  File "/private/home/aqib/fairo/agents/droidlet_agent.py", line 340, in process_language_perception
    self.memory.get_player_by_name(speaker).memid, preprocessed_chat
AttributeError: 'NoneType' object has no attribute 'memid'
Traceback (most recent call last):
  File "agents/craftassist/craftassist_agent.py", line 560, in <module>
    sa.start()
  File "/private/home/aqib/fairo/agents/core.py", line 23, in start
    self.handle_exception(e)
  File "/private/home/aqib/fairo/agents/droidlet_agent.py", line 296, in handle_exception
    raise e
  File "/private/home/aqib/fairo/agents/core.py", line 21, in start
    self.step()
  File "/private/home/aqib/fairo/agents/droidlet_agent.py", line 301, in step
    super().step()
  File "/private/home/aqib/fairo/agents/core.py", line 26, in step
    self.perceive()
  File "agents/craftassist/craftassist_agent.py", line 275, in perceive
    super().perceive()
  File "/private/home/aqib/fairo/agents/droidlet_agent.py", line 366, in perceive
    self.process_language_perception(speaker, chat, preprocessed_chat, chat_parse)
  File "/private/home/aqib/fairo/agents/droidlet_agent.py", line 340, in process_language_perception
    self.memory.get_player_by_name(speaker).memid, preprocessed_chat
AttributeError: 'NoneType' object has no attribute 'memid'
```

This boils down to `get_player_by_name(speaker)` fetching Nothing when looking for my username (aqibisbiqa). Could this be due to the PlayerNode associated with my MC player not being properly registered into memory?

## Current Behavior

Supposed to be able to send commands through MC chat

## Expected Behavior

Can't send commands through MC chat to Craftassist agent

## Steps to reproduce

After all the typical port forwarding/tunneling and starting the cuberite_process and craftassist_agent, connect to the server using Minecraft v1.12.2. The porting config I used was "18888:25565", so I connect using localhost:18888. Once in the server, press 'T' to open chat and send any command (i.e. "dig a hole", "build a rectangle")

## Checklist

Use this checklist if you are using this issue as a tracker:

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3 ...

**Comment by aszlam** [comment]
can you check you are waiting long enough for the agent to initialize?  I just ran from main and it seems ok.

**Comment by aqibisbiqa** [comment]
Yeah I think that was the issue. You have to wait for this message to load before sending any commands:
```
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray. fn = np.random.choice(fns, p=p)
```
