### ISSUE TITLE
Breakage from Querying Selection of all Reference Objects without WHERE Clause

### ISSUE THREAD

**Issue by aqibisbiqa** [facebookresearch/fairo#1192]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

Title explains issue. Motivation due to this error:

```
TypeError: cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "agents/craftassist/craftassist_agent.py", line 568, in <module>
    sa.start()
  File "/private/home/aqib/fairo/agents/core.py", line 23, in start
    self.handle_exception(e)
  File "/private/home/aqib/fairo/agents/droidlet_agent.py", line 296, in handle_exception
    raise e
  File "/private/home/aqib/fairo/agents/core.py", line 21, in start
    self.step()
  File "/private/home/aqib/fairo/agents/droidlet_agent.py", line 301, in step
    super().step()
  File "/private/home/aqib/fairo/agents/core.py", line 26, in step
    self.perceive()
  File "agents/craftassist/craftassist_agent.py", line 298, in perceive
    self.draw_map_to_dashboard()
  File "agents/craftassist/craftassist_agent.py", line 414, in draw_map_to_dashboard
    detections_for_map = self.get_detected_objects_for_map()
  File "agents/craftassist/craftassist_agent.py", line 399, in get_detected_objects_for_map
    search_res = self.memory.basic_search("SELECT MEMORY FROM ReferenceObject")
  File "/private/home/aqib/fairo/droidlet/memory/sql_memory.py", line 369, in basic_search
    return self.searcher.search(self, query=query, get_all=get_all)
  File "/private/home/aqib/fairo/droidlet/memory/memory_filters.py", line 516, in search
    vals = self.handle_output(agent_memory, query, memids, get_all)
  File "/private/home/aqib/fairo/droidlet/memory/memory_filters.py", line 451, in handle_output
    return [agent_memory.get_mem_by_id(m) for m in memids]
  File "/private/home/aqib/fairo/droidlet/memory/memory_filters.py", line 451, in <listcomp>
    return [agent_memory.get_mem_by_id(m) for m in memids]
  File "/private/home/aqib/fairo/droidlet/memory/sql_memory.py", line 305, in get_mem_by_id
    return self.nodes.get(node_type, MemoryNode)(self, memid)
  File "/private/home/aqib/fairo/droidlet/memory/memory_nodes.py", line 690, in __init__
    super().__init__(agent_memory, memid)
  File "/private/home/aqib/fairo/droidlet/memory/memory_nodes.py", line 624, in __init__
    "SELECT x, y, z FROM ReferenceObjects WHERE uuid=?", self.memid
TypeError: cannot unpack non-iterable NoneType object
```

## Current Behavior

See error message above.

## Expected Behavior

A selection query from the ReferenceObjects relation should not result in errors

## Steps to reproduce

First `git checkout -b aqib 74b38e1baebcd586d20af254553c0180d44e4703`.

Then in `agents/craftassist/craftassist_agent.py` line 400, remove `WHERE y>-500` from the line 
```search_res = self.memory.basic_search("SELECT MEMORY FROM ReferenceObject WHERE y>-500")```

The dashboard should properly display detected obstacles upon first initialization, but if you issue a command to the agent to change elevation (i.e. `dig a hole`), the necessary update to detected obstacles yields in a query selection error.

## Links to any relevant pastes or documents 

n/a

## Checklist

Use this checklist if you are using this issue as a tracker:

- [ ] Task 1
- [ ] Task 2
- [ ] Task 3 ...

**Comment by kavyasrinet** [comment]
@aqibisbiqa can you paste the command to repro this ?

**Comment by aqibisbiqa** [comment]
Ah ok, this issue needs some updating.

Arthur suggested that I could bypass this issue by adding a dummy WHERE clause to the query that caused the problem. Originally, the code was:
```
def get_detected_objects_for_map(self):
    search_res = self.memory.basic_search("SELECT MEMORY FROM ReferenceObject")
```

But I've since altered it to this:
```
def get_detected_objects_for_map(self):
    # FIXME should not be using WHERE clause hack
    search_res = self.memory.basic_search("SELECT MEMORY FROM ReferenceObject WHERE y>-500")
```

So while the issue doesn't appear anymore on my branch, this is still something that exists. To reproduce, the extra step to do now is remove the "WHERE y>-500" part from the query, and then run the dashboard + cuberite + agent and issue the command `dig a hole`. I've updated the corresponding section as well

**Comment by aszlam** [comment]
closed in https://github.com/facebookresearch/fairo/pull/1200
