### ISSUE TITLE
[Polymetis] Error when running examples (cannot find torchscript_pinocchio)

### ISSUE THREAD

**Issue by paarthshah-tri** [facebookresearch/fairo#1304]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

Issue when trying to run Polymetis Controllers

## Current Behavior

When trying to run (for example) the 0_set_joint_position.py, I get the following error:

```
Warning: Failed to load 'libtorchscript_pinocchio.so' from CONDA_PREFIX, loading 
from default build directory instead: '/home/panda/Applications/fairo/polymetis/polymetis/build/torch_isolation/libtorchscript_pinocchio.so'
Traceback (most recent call last):
  File "/home/panda/Applications/fairo/polymetis/polymetis/python/torchcontrol/models/torchscript_pinocchio.py", line 12, in <module>
    torch.classes.load_library(
  File "/home/panda/.local/lib/python3.8/site-packages/torch/_classes.py", line 48, in load_library
    torch.ops.load_library(path)
  File "/home/panda/.local/lib/python3.8/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/home/panda/anaconda3/envs/polymetis-local/lib/python3.8/ctypes/__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/panda/anaconda3/envs/polymetis-local/lib/libtorchscript_pinocchio.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "0_set_joint_positions.py", line 7, in <module>
    from polymetis import RobotInterface
  File "/home/panda/Applications/fairo/polymetis/polymetis/python/polymetis/__init__.py", line 6, in <module>
    from .robot_interface import RobotInterface
  File "/home/panda/Applications/fairo/polymetis/polymetis/python/polymetis/robot_interface.py", line 20, in <module>
    import torchcontrol as toco
  File "/home/panda/Applications/fairo/polymetis/polymetis/python/torchcontrol/__init__.py", line 7, in <module>
    from . import models
  File "/home/panda/Applications/fairo/polymetis/polymetis/python/torchcontrol/models/__init__.py", line 5, in <module>
    from .torchscript_pinocchio import RobotModelPinocchio
  File "/home/panda/Applications/fairo/polymetis/polymetis/python/torchcontrol/models/torchscript_pinocchio.py", line 25, in <module>
    torch.classes.load_library(lib_path)
  File "/home/panda/.local/lib/python3.8/site-packages/torch/_classes.py", line 48, in load_library
    torch.ops.load_library(path)
  File "/home/panda/.local/lib/python3.8/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/home/panda/anaconda3/envs/polymetis-local/lib/python3.8/ctypes/__init__.py", line 369, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/panda/Applications/fairo/polymetis/polymetis/build/torch_isolation/libtorchscript_pinocchio.so: undefined symbol: _ZNK3c104Type14isSubtypeOfExtERKSt10shared_ptrIS0_EPSo
```

I've tried both building from source and using the conda install instructions only to get the same error.

## Expected Behavior

This should run the script and send joint commands.

**Comment by exhaustin** [comment]
Hello @paarthshah-tri, are you installing Polymetis from source? If so please refer to  #1278
If you are installing our prebuilt conda package, try to create a clean environment and reinstall Polymetis into it.

**Comment by paarthshah-tri** [comment]
Hi @exhaustin ,

I tried both from source and using the prebuilt conda package. Both resulted in the same error. I also tried the suggestion in #1278 but restarting and building from a clean build folder didn't help unfortunately.

**Comment by paarthshah-tri** [comment]
Fixed this by creating a new account.
