### ISSUE TITLE
AttributeError: register

### ISSUE THREAD

**Issue by ruinianxu** [facebookresearch/fairo#1327]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description
When run ```nsp_retrain_infra.py``` to train a new model, I got the following error,

```
Traceback (most recent call last):
  File "/private/home/simonxu/.conda/envs/droidlet_env/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/private/home/simonxu/.conda/envs/droidlet_env/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "droidlet/tools/hitl/nsp_retrain_infra.py", line 313, in run
    download_dir, config_dir = self.download_data(opts, batch_id)
  File "droidlet/tools/hitl/nsp_retrain_infra.py", line 144, in download_data
    opts=opts, batch_id=batch_id, data_filepath=annotated_filepath
  File "droidlet/tools/hitl/nsp_retrain_infra.py", line 251, in create_mask
    self._job_mng_util.set_job_stat(Job.register, JobStat.NEW_DATA_SZ, total_rows)
  File "/private/home/simonxu/.conda/envs/droidlet_env/lib/python3.7/enum.py", line 346, in __getattr__
    raise AttributeError(name) from None
AttributeError: register
```

## Steps to reproduce

Run 
```
python droidlet/tools/hitl/nsp_retrain_infra.py --batch_id 202206281309 --retrain_data_splits 2 2 2 --num_epochs 100 -decoder_learning_rate .00000001 .00000005 .0000001 .0000005 .000001 .000005 .00001 .00005 .0001 -encoder_learning_rate .0 .00000001 .00000005 .0000001 .0000005 .000001 .000005 .00001 .00005 .0001 --batch_size 8 --param_update_freq 3 --new_data_training_threshold 0 --use_32g_gpu --encoder_warmup_steps 1 --decoder_warmup_steps 1000
```

**Comment by ruinianxu** [comment]
I've tested with previous commit and it works. The error comes from Job definition in hitl_recorder.py.

**Comment by mialsy** [comment]
> I've tested with previous commit and it works. The error comes from Job definition in hitl_recorder.py.

Thanks for creating the issue, I will update code to address this issue in the PR #1326

**Comment by mialsy** [comment]
This has been fixed with https://github.com/facebookresearch/fairo/pull/1326, so I will close this issue. Let me know if there is further problem.
