### ISSUE TITLE
Cannot initialize franka gripper server

### ISSUE THREAD

**Issue by yuchen93** [facebookresearch/fairo#1356]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)

## Description

Launch gripper script aborts with SIGABRT: 6

## Current Behavior

After launching the server, Franka gripper homes but then aborts.

```
 launch_gripper.py gripper=franka_hand

Gripper server running at 0.0.0.0:50052.
[2022-08-24 13:09:04,031][polymetis.robot_client.executable_robot_client][INFO] - === Config: ===
exec: franka_hand_client
robot_ip: 172.16.0.2
control_ip: 0.0.0.0
control_port: 50052
robot_client_metadata_path: /tmp/tmp2zvqvk12

[2022-08-24 13:09:04,032][polymetis.robot_client.executable_robot_client][INFO] - === Executing client at /home/.../bin/franka_hand_client ===
[2022-08-24 13:09:04.050] [info] Connecting to robot_ip 172.16.0.2
terminate called without an active exception
[2022-08-24 13:09:10.721] [info] Moving to width 0 at speed=0
Traceback (most recent call last):
  File "/home/.../bin/launch_gripper.py", line 44, in <module>
    main()
  File "/home/.../lib/python3.8/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/home.../lib/python3.8/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/home.../lib/python3.8/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/home/...lib/python3.8/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/home.../lib/python3.8/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/home/.../lib/python3.8/site-packages/hydra/_internal/hydra.py", line 107, in run
    return run_job(
  File "/home/.../lib/python3.8/site-packages/hydra/core/utils.py", line 127, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/.../bin/launch_gripper.py", line 40, in main
    gripper_client.run()
  File "/home.../lib/python3.8/site-packages/polymetis/robot_client/executable_robot_client.py", line 78, in run
    subprocess.run(
  File "/home/.../lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/.../bin/franka_hand_client', '/tmp/tmp_vbzkofo']' died with <Signals.SIGABRT: 6>.
```

Additionally this also fails: 
franka_hand_client tmp-gripper.yaml 
[2022-08-24 13:28:32.232] [info] Connecting to robot_ip 172.16.0.2
terminate called without an active exception
[2022-08-24 13:28:38.947] [info] Moving to width 0 at speed=0
Aborted (core dumped)

tmp-gripper.yaml:
```
exec: franka_hand_client
robot_ip: "172.16.0.2"
control_ip: "localhost"
control_port: 50052
```

## Expected Behavior

Connects to gripper.

`launch_gripper.py gripper=franka_hand`

**Comment by 1heart** [comment]
It looks like something went wrong during compilation. Are you using the conda package or a local build?

I would suggest doing a fresh local build (i.e. instructions [here](https://facebookresearch.github.io/fairo/polymetis/installation.html#from-source)) with the [libfranka corresponding to your fci version](https://frankaemika.github.io/docs/compatibility.html) checked out. Please let me know the results.

**Comment by yuchen93** [comment]
I previously installed with mamba but just tried reinstalling from source, the error is still there. I am able to launch the robot part just find so I don't think it is a fci/libfranka version issue.

I additionally ran franka_hand_client with gdb and this is the output:
```
Starting program: /home/.../polymetis/fairo/polymetis/polymetis/build/franka_hand_client tmp-gripper.yaml
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6930700 (LWP 437068)]
[New Thread 0x7fffeffff700 (LWP 437069)]
[New Thread 0x7ffff612f700 (LWP 437070)]
[2022-08-25 13:07:15.709] [info] Connecting to robot_ip 172.16.0.2
[New Thread 0x7ffff592e700 (LWP 437074)]
[New Thread 0x7ffff512d700 (LWP 437075)]
terminate called without an active exception
[2022-08-25 13:07:22.260] [info] Moving to width 0 at speed=0

Thread 1 "franka_hand_cli" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

(gdb) where
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff774d859 in __GI_abort () at abort.c:79
#2  0x00007ffff79e8036 in __gnu_cxx::__verbose_terminate_handler ()
    at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff79e6524 in __cxxabiv1::__terminate (handler=<optimized out>)
    at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007ffff79e6576 in std::terminate ()
    at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x0000555555568735 in FrankaHandClient::run() ()
#6  0x0000555555567d17 in main ()

```
Let me know what I should try next!

**Comment by exhaustin** [comment]
This issue should be fixed in the latest main, please update the conda package, or pull & reinstall if using a local build.
Feel free to reopen if issue persists.
