### ISSUE TITLE
'GripperInterface' object has no attribute 'metadata'

### ISSUE THREAD

**Issue by Ynao3** [facebookresearch/fairo#1422]
WARNING:polymetis.gripper_interface:Metadata unavailable from server.
ERROR:zerorpc.core:
Traceback (most recent call last):
  File "/home/zhu/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/zhu/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/zhu/anaconda3/envs/polymetis-local/lib/python3.8/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/home/zhu/droid/droid/franka/robot.py", line 38, in launch_robot
    self._max_gripper_width = self._gripper.metadata.max_width
AttributeError: 'GripperInterface' object has no attribute 'metadata'
/home/zhu/droid/droid/franka/launch_gripper.sh: line 4: 31129 Killed

**Comment by GabrielZH** [comment]
Hi, I encountered exactly the same issue as yours. May I ask if you have figured out the culprit and resolved it?

**Comment by y556zhao** [comment]
same here.

**Comment by kingchou007** [comment]
same here
