### ISSUE TITLE
"spawn a chicken" doesn't work

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/fairo#783]
## Type of Issue

Select the type of issue:
- [x] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

branch name : `kavya_frl_demo`
Input : "spawn a chicken"

```
INFO:root:Incoming chats: ['<ScoobyDooby12> spawn a chicken']
2021-11-03 17:06:55,829 [nsp_querier.py:81 - perceive() INFO]: Incoming chats: ['<ScoobyDooby12> spawn a chicken']
INFO:root:Found ground truth action for "spawn a chicken"
2021-11-03 17:06:55,830 [nsp_querier.py:187 - get_logical_form() INFO]: Found ground truth action for "spawn a chicken"
INFO:root:logical form post co-ref and process_spans "44e3be4a5fc422cbfcf4b6aaa19f1244d5d7f69b6c00b11c59373d80af3ac71b:30a44eea95664617963ca44bc26ed2f9" -> {'dialogue_type': 'HUMAN_GIVE_COMMAND', 'action_sequence': [{'reference_object': {'filters': {'where_clause': {'AND': [{'pred_text': 'has_name', 'obj_text': 'chicken'}]}}}, 'action_type': 'SPAWN'}]}
2021-11-03 17:06:55,848 [map_to_dialogue_object.py:132 - postprocess_logical_form() INFO]: logical form post co-ref and process_spans "44e3be4a5fc422cbfcf4b6aaa19f1244d5d7f69b6c00b11c59373d80af3ac71b:30a44eea95664617963ca44bc26ed2f9" -> {'dialogue_type': 'HUMAN_GIVE_COMMAND', 'action_sequence': [{'reference_object': {'filters': {'where_clause': {'AND': [{'pred_text': 'has_name', 'obj_text': 'chicken'}]}}}, 'action_type': 'SPAWN'}]}
ERROR:root:Default handler caught exception, db_log_idx=116560
Traceback (most recent call last):
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 21, in start
    self.step()
  File "/private/home/kavyasrinet/droidlet/agents/droidlet_agent.py", line 253, in step
    super().step()
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 29, in step
    self.controller_step()
  File "/private/home/kavyasrinet/droidlet/agents/droidlet_agent.py", line 350, in controller_step
    obj.step(self)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/interpreter.py", line 144, in step
    r = self.action_handlers[action_type](agent, self.speaker, action_def)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/craftassist/mc_interpreter.py", line 177, in handle_spawn
    object_idms = interpret_mob_schematic(self, speaker, filters_d)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/craftassist/interpret_schematic.py", line 296, in interpret_mob_schematic
    if filters_d["selector"].get("same", "ALLOWED") == "DISALLOWED":
KeyError: 'selector'
2021-11-03 17:06:55,855 [droidlet_agent.py:231 - handle_exception() ERROR]: Default handler caught exception, db_log_idx=116560
Traceback (most recent call last):
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 21, in start
    self.step()
  File "/private/home/kavyasrinet/droidlet/agents/droidlet_agent.py", line 253, in step
    super().step()
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 29, in step
    self.controller_step()
  File "/private/home/kavyasrinet/droidlet/agents/droidlet_agent.py", line 350, in controller_step
    obj.step(self)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/interpreter.py", line 144, in step
    r = self.action_handlers[action_type](agent, self.speaker, action_def)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/craftassist/mc_interpreter.py", line 177, in handle_spawn
    object_idms = interpret_mob_schematic(self, speaker, filters_d)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/craftassist/interpret_schematic.py", line 296, in interpret_mob_schematic
    if filters_d["selector"].get("same", "ALLOWED") == "DISALLOWED":
KeyError: 'selector'
Traceback (most recent call last):
  File "agents/craftassist/craftassist_agent.py", line 521, in <module>
    sa.start()
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 23, in start
    self.handle_exception(e)
  File "/private/home/kavyasrinet/droidlet/agents/droidlet_agent.py", line 248, in handle_exception
    raise e
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 21, in start
    self.step()
  File "/private/home/kavyasrinet/droidlet/agents/droidlet_agent.py", line 253, in step
    super().step()
  File "/private/home/kavyasrinet/droidlet/agents/core.py", line 29, in step
    self.controller_step()
  File "/private/home/kavyasrinet/droidlet/agents/droidlet_agent.py", line 350, in controller_step
    obj.step(self)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/interpreter.py", line 144, in step
    r = self.action_handlers[action_type](agent, self.speaker, action_def)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/craftassist/mc_interpreter.py", line 177, in handle_spawn
    object_idms = interpret_mob_schematic(self, speaker, filters_d)
  File "/private/home/kavyasrinet/droidlet/droidlet/interpreter/craftassist/interpret_schematic.py", line 296, in interpret_mob_schematic
    if filters_d["selector"].get("same", "ALLOWED") == "DISALLOWED":
KeyError: 'selector'
```

**Comment by aszlam** [comment]
closing this, its fixed on the frl_demo branch and will merge to main after
