### ISSUE TITLE
max_steps not hit on memory error

### ISSUE THREAD

**Issue by ethan-carlson** [facebookresearch/fairo#786]
## Type of Issue

Select the type of issue:
- [X] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Description

Before dialogue_object and dialogue_stack were deprecated (#757), if the agent encountered a memory bug as in issue [#340](https://github.com/facebookresearch/fairo/issues/340) it would crash after max_steps.  Now it enters an infinite loop.

## Current Behavior

The agent will try to execute a bad task infinitely.

## Expected Behavior

Agent should exit task and/or program after max_steps.

## Steps to reproduce

Eg. Issue a bad "tag" command with no referent.  Must have --agent_debug_mode tag on.

## Links to any relevant pastes or documents 

**Stack trace from infinite loop**

2021-11-04 21:31:59,977 [sql_memory.py:1054 - _db_write() ERROR]: Bad write: 
                    INSERT INTO Schematics(uuid, x, y, z, bid, meta)
                    VALUES (?, ?, ?, ?, ?, ?) : ('cb72eaff804e497ca68e487f3b4ece30', 2, 63, 10, None, None)
ERROR:root:Default handler caught exception, db_log_idx=147626
Traceback (most recent call last):
  File "/fairo/agents/core.py", line 21, in start
    self.step()
  File "/fairo/agents/droidlet_agent.py", line 271, in step
    super().step()
  File "/fairo/agents/core.py", line 29, in step
    self.controller_step()
  File "/fairo/agents/droidlet_agent.py", line 368, in controller_step
    obj.step(self)
  File "/fairo/droidlet/interpreter/craftassist/put_memory_handler.py", line 56, in step
    r = self._step(agent)
  File "/fairo/droidlet/interpreter/craftassist/put_memory_handler.py", line 74, in _step
    return self.handle_triple(agent)
  File "/fairo/droidlet/interpreter/craftassist/put_memory_handler.py", line 114, in handle_triple
    self.memory.convert_block_object_to_schematic(mem.memid).memid
  File "/fairo/droidlet/memory/craftassist/mc_memory.py", line 621, in convert_block_object_to_schematic
    memid = SchematicNode.create(self, list(block_object.blocks.items()))
  File "/fairo/droidlet/memory/craftassist/mc_memory_nodes.py", line 545, in create
    memory.db_write(
  File "/fairo/droidlet/memory/sql_memory.py", line 1013, in db_write
    r = self._db_write(query, *args)
  File "/fairo/droidlet/memory/sql_memory.py", line 1048, in _db_write
    c.execute(query, args)
sqlite3.IntegrityError: NOT NULL constraint failed: Schematics.bid
2021-11-04 21:31:59,977 [droidlet_agent.py:247 - handle_exception() ERROR]: Default handler caught exception, db_log_idx=147626
Traceback (most recent call last):
  File "/fairo/agents/core.py", line 21, in start
    self.step()
  File "/fairo/agents/droidlet_agent.py", line 271, in step
    super().step()
  File "/fairo/agents/core.py", line 29, in step
    self.controller_step()
  File "/fairo/agents/droidlet_agent.py", line 368, in controller_step
    obj.step(self)
  File "/fairo/droidlet/interpreter/craftassist/put_memory_handler.py", line 56, in step
    r = self._step(agent)
  File "/fairo/droidlet/interpreter/craftassist/put_memory_handler.py", line 74, in _step
    return self.handle_triple(agent)
  File "/fairo/droidlet/interpreter/craftassist/put_memory_handler.py", line 114, in handle_triple
    self.memory.convert_block_object_to_schematic(mem.memid).memid
  File "/fairo/droidlet/memory/craftassist/mc_memory.py", line 621, in convert_block_object_to_schematic
    memid = SchematicNode.create(self, list(block_object.blocks.items()))
  File "/fairo/droidlet/memory/craftassist/mc_memory_nodes.py", line 545, in create
    memory.db_write(
  File "/fairo/droidlet/memory/sql_memory.py", line 1013, in db_write
    r = self._db_write(query, *args)
  File "/fairo/droidlet/memory/sql_memory.py", line 1048, in _db_write
    c.execute(query, args)
sqlite3.IntegrityError: NOT NULL constraint failed: Schematics.bid
INFO:root:update_recent_entities [<droidlet.memory.memory_nodes.AttentionNode object at 0x7fe2607a79d0>]
2021-11-04 21:31:59,982 [sql_memory.py:225 - update_recent_entities() INFO]: update_recent_entities [<droidlet.memory.memory_nodes.AttentionNode object at 0x7fe2607a79d0>]
INFO:root:update_recent_entities [<droidlet.memory.memory_nodes.AttentionNode object at 0x7fe2607a7fd0>]
2021-11-04 21:31:59,984 [sql_memory.py:225 - update_recent_entities() INFO]: update_recent_entities [<droidlet.memory.memory_nodes.AttentionNode object at 0x7fe2607a7fd0>]
ERROR:root:Bad write: 
                    INSERT INTO Schematics(uuid, x, y, z, bid, meta)
                    VALUES (?, ?, ?, ?, ?, ?) : ('01bb5065f381462f95312c72df3e59dc', 2, 63, 10, None, None)

etc. etc. 

Top of the stack trace with the logical form: https://www.internalfb.com/phabricator/paste/view/P466617901

**Comment by aszlam** [comment]
could you append the parse that led here?  I will put some checks in but want to make sure that I hit the path from the parse

**Comment by aszlam** [comment]
I was unable to repro, and error trace suggests a bug in grabbing the VoxelObject rather than in the PutMemory handler.  @ethan-carlson more context would be useful

**Comment by ethan-carlson** [comment]
@aszlam apologies, I didn't have enough info in the description to repro.  You have to have the --agent_debug_mode on for the bug to appear.

**Comment by ethan-carlson** [comment]
> could you append the parse that led here? I will put some checks in but want to make sure that I hit the path from the parse

Here you go: https://www.internalfb.com/phabricator/paste/view/P466617901
