### ISSUE TITLE
ModuleNotFoundError: No module named 'quaternion'

### ISSUE THREAD

**Issue by kavyasrinet** [facebookresearch/fairo#791]
## Type of Issue

Select the type of issue:
- [ ] Bug report (to report a bug)
- [ ] Feature request (to request an additional feature)
- [ ] Tracker (I am just using this as a tracker)
- [ ] Refactor request
- [ ] Documentation Ask

## Steps to reproduce
from `agents/locobot`:

```
mamba install https://anaconda.org/aihabitat/habitat-sim/0.2.1/download/linux-64/habitat-sim-0.2.1-py3.7_headless_linux_fc7fb11ccec407753a73ab810d1dbb5f57d0f9b9.tar.bz2
cd ../../droidlet/lowlevel/locobot/remote
./launch_pyro_habitat.sh
```

Stack trace:
```
(droidlet_env) kavyasrinet@devfair0228:~/droidlet/droidlet/lowlevel/locobot/remote$ ./launch_pyro_habitat.sh
bash: /public/apps/anaconda3/2020.11/lib/libtinfo.so.6: no version information available (required by bash)
++ dirname ./launch_pyro_habitat.sh
+ pushd .
~/droidlet/droidlet/lowlevel/locobot/remote ~/droidlet/droidlet/lowlevel/locobot/remote
+ export PYRO_SERIALIZER=pickle
+ PYRO_SERIALIZER=pickle
+ export PYRO_SERIALIZERS_ACCEPTED=pickle
+ PYRO_SERIALIZERS_ACCEPTED=pickle
+ export PYRO_SOCK_REUSE=True
+ PYRO_SOCK_REUSE=True
+ echo 'Kill matching processes...'
Kill matching processes...
+ ./kill_pyro_habitat.sh
bash: /public/apps/anaconda3/2020.11/lib/libtinfo.so.6: no version information available (required by bash)
Killing navigation, planning, slam, remote and naming processes
+ echo 'Launching environment ...'
Launching environment ...
++ hostname -I
++ cut -f1 '-d '
+ default_ip=100.97.69.170
+ ip=100.97.69.170
+ export LOCAL_IP=100.97.69.170
+ LOCAL_IP=100.97.69.170
+ export LOCOBOT_IP=100.97.69.170
+ LOCOBOT_IP=100.97.69.170
+ echo 'Binding to Host IP' 100.97.69.170
Binding to Host IP 100.97.69.170
+ BGPID=73935
+ sleep 4
+ python -m Pyro4.naming -n 100.97.69.170
Broadcast server running on 0.0.0.0:9091
NS running on 100.97.69.170:9090 (100.97.69.170)
Warning: HMAC key not set. Anyone can connect to this server!
URI = PYRO:Pyro.NameServer@100.97.69.170:9090
+ echo 100.97.69.170
100.97.69.170
+ timeout 1m bash -c 'until python check_connected.py remotelocobot; do sleep 1; done;'
+ python remote_locobot.py --ip 100.97.69.170
bash: /public/apps/anaconda3/2020.11/lib/libtinfo.so.6: no version information available (required by bash)
backend_config {'scene_path': '/Replica-Dataset/apartment_0/habitat/mesh_semantic.ply', 'physics_config': '/private/home/kavyasrinet/droidlet/droidlet/lowlevel/locobot/tests/test_assets/default.phys_scene_config.json', 'noisy': False}
Traceback (most recent call last):
  File "remote_locobot.py", line 451, in <module>
    noisy=args.noisy,
  File "remote_locobot.py", line 48, in __init__
    self.restart_habitat()
  File "remote_locobot.py", line 58, in restart_habitat
    self._robot = Robot("habitat", common_config=backend_config)
  File "/private/home/kavyasrinet/droidlet/droidlet/lowlevel/locobot/remote/pyrobot/core.py", line 97, in __init__
    mod = importlib.import_module(root_node + self.configs.COMMON.NAME)
  File "/private/home/kavyasrinet/.conda/envs/droidlet_env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/private/home/kavyasrinet/droidlet/droidlet/lowlevel/locobot/remote/pyrobot/habitat/simulator.py", line 6, in <module>
    from pyrobot.habitat.sim_utils import make_cfg
  File "/private/home/kavyasrinet/droidlet/droidlet/lowlevel/locobot/remote/pyrobot/habitat/sim_utils.py", line 7, in <module>
    import habitat_sim
  File "/private/home/kavyasrinet/.conda/envs/droidlet_env/lib/python3.7/site-packages/habitat_sim/__init__.py", line 13, in <module>
    from habitat_sim import (
  File "/private/home/kavyasrinet/.conda/envs/droidlet_env/lib/python3.7/site-packages/habitat_sim/agent/__init__.py", line 9, in <module>
    from .agent import *  # noqa: F403
  File "/private/home/kavyasrinet/.conda/envs/droidlet_env/lib/python3.7/site-packages/habitat_sim/agent/agent.py", line 12, in <module>
    import quaternion as qt
ModuleNotFoundError: No module named 'quaternion'

```

**Comment by kavyasrinet** [comment]
This should get fixed when we revamp the locobot setup without needing a docker image
